name: braillekeyboardgame
description: Braile app

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_icons: ^1.1.0
  #Firebase Related
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  cloud_firestore: ^0.13.4+2
  firebase_auth:
  google_sign_in:
  font_awesome_flutter: ^8.8.1
  flutter_facebook_login:
  #Firebase end
  flutter_progress_button: ^1.0.0
  audioplayers: ^0.14.1
  country_icons: ^1.1.1
  shared_preferences: ^0.5.7

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/pop.mp3
    - assets/audio/space.mp3
    - assets/audio/delete.m4a
    - assets/json/keyboard.json
    - assets/json/number.json
    - assets/bicon.png
    - assets/google.png
    - assets/facebook.png
    - assets/logo.png
    - assets/icon.jpg
